#!/usr/bin/env python3

"""
Preprocess a standalone audio dataset (audio files with NO accompanying video).

This script mirrors ``process_dataset.py`` but for audio-only clips (e.g. sounds
downloaded from freesound or generated by MMAudio). It computes:
  - text caption embeddings  -> conditions/
  - audio latents            -> audio_latents/

Crucially, it does NOT write any video ``latents/`` files. The absence of a
matching ``latents/`` file is what signals to ``PrecomputedDataset`` (with
``include_audio_only=True``) that the sample is audio-only, so it can be mixed
into the same training run as regular video / video+audio samples.

The dataset must be a CSV, JSON, or JSONL file with columns for captions and
audio paths (same schema as the video dataset, but ``media_path`` points at an
audio file such as ``.wav``/``.mp3``/``.flac``).

Basic usage:
    python scripts/process_audio.py /path/to/dataset.csv \
        --model-path /path/to/ltx2.safetensors --text-encoder-path /path/to/gemma
"""

import json
from pathlib import Path
from typing import Any

import pandas as pd
import torch
import torchaudio
import typer
from process_videos import encode_audio
from rich.console import Console
from rich.progress import (
    BarColumn,
    MofNCompleteColumn,
    Progress,
    SpinnerColumn,
    TaskProgressColumn,
    TextColumn,
    TimeElapsedColumn,
    TimeRemainingColumn,
)
from torch.utils.data import DataLoader, Dataset

from ltx_core.model.audio_vae import AudioProcessor
from ltx_core.types import Audio
from ltx_trainer import logger
from ltx_trainer.gpu_utils import free_gpu_memory_context
from ltx_trainer.model_loader import load_audio_vae_encoder, resolve_audio_vae_path

console = Console()

app = typer.Typer(
    pretty_exceptions_enable=False,
    no_args_is_help=True,
    help="Preprocess a standalone audio dataset (audio-only clips) into conditions/ and audio_latents/. "
    "The dataset must be a CSV, JSON, or JSONL file with columns for captions and audio paths.",
)


class AudioDataset(Dataset):
    """Dataset that loads standalone audio waveforms (no video) for encoding."""

    def __init__(
        self,
        dataset_file: str | Path,
        audio_column: str,
        max_duration: float | None = None,
    ) -> None:
        """
        Args:
            dataset_file: Path to CSV/JSON/JSONL metadata file
            audio_column: Column name for audio file paths in the metadata file
            max_duration: Optional cap (seconds) to trim long clips and bound memory use
        """
        super().__init__()
        self.dataset_file = Path(dataset_file)
        self.audio_column = audio_column
        self.max_duration = max_duration
        self.audio_paths = self._load_audio_paths(audio_column)

    def __len__(self) -> int:
        return len(self.audio_paths)

    def __getitem__(self, index: int) -> dict[str, Any]:
        audio_path: Path = self.audio_paths[index]

        data_root = self.dataset_file.parent
        relative_path = str(audio_path.relative_to(data_root))

        waveform, sample_rate = torchaudio.load(str(audio_path))

        # Optionally trim to a maximum duration to bound memory use.
        if self.max_duration is not None:
            max_samples = int(self.max_duration * sample_rate)
            if waveform.shape[-1] > max_samples:
                waveform = waveform[..., :max_samples]

        return {
            "waveform": waveform,
            "sample_rate": sample_rate,
            "relative_path": relative_path,
        }

    def _load_audio_paths(self, column: str) -> list[Path]:
        """Load audio paths from the specified data source."""
        if self.dataset_file.suffix == ".csv":
            entries = self._load_column_from_csv(column)
        elif self.dataset_file.suffix == ".json":
            entries = self._load_column_from_json(column)
        elif self.dataset_file.suffix == ".jsonl":
            entries = self._load_column_from_jsonl(column)
        else:
            raise ValueError("Expected `dataset_file` to be a path to a CSV, JSON, or JSONL file.")

        data_root = self.dataset_file.parent
        audio_paths = [data_root / Path(entry.strip()) for entry in entries]

        invalid_paths = [path for path in audio_paths if not path.is_file()]
        if invalid_paths:
            raise ValueError(f"Found {len(invalid_paths)} invalid audio paths. First few: {invalid_paths[:5]}")

        return audio_paths

    def _load_column_from_csv(self, column: str) -> list[str]:
        df = pd.read_csv(self.dataset_file)
        if column not in df.columns:
            raise ValueError(f"Column '{column}' not found in CSV file")
        return [str(v) for v in df[column].tolist()]

    def _load_column_from_json(self, column: str) -> list[str]:
        with open(self.dataset_file, "r", encoding="utf-8") as file:
            data = json.load(file)
        if not isinstance(data, list):
            raise ValueError("JSON file must contain a list of objects")
        values = []
        for entry in data:
            if column not in entry:
                raise ValueError(f"Key '{column}' not found in JSON entry")
            values.append(str(entry[column]))
        return values

    def _load_column_from_jsonl(self, column: str) -> list[str]:
        values = []
        with open(self.dataset_file, "r", encoding="utf-8") as file:
            for line in file:
                entry = json.loads(line)
                if column not in entry:
                    raise ValueError(f"Key '{column}' not found in JSONL entry")
                values.append(str(entry[column]))
        return values


def compute_audio_latents(
    dataset_file: str | Path,
    audio_column: str,
    output_dir: str,
    model_path: str,
    audio_vae_path: str | None = None,
    device: str = "cuda",
    max_duration: float | None = None,
) -> None:
    """Encode standalone audio files and save audio latents.

    Args:
        dataset_file: Path to metadata file (CSV/JSON/JSONL) containing audio paths
        audio_column: Column name for audio paths in the metadata file
        output_dir: Directory to save audio latents
        model_path: Path to LTX-2 checkpoint (.safetensors)
        device: Device to use for computation
        max_duration: Optional cap (seconds) to trim long clips
    """
    torch_device = torch.device(device)

    dataset = AudioDataset(dataset_file=dataset_file, audio_column=audio_column, max_duration=max_duration)
    logger.info(f"Loaded {len(dataset)} audio files")

    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    audio_vae_file = resolve_audio_vae_path(model_path, audio_vae_path)
    with console.status(f"[bold]Loading audio VAE encoder from [cyan]{audio_vae_file}[/]...", spinner="dots"):
        audio_vae_encoder = load_audio_vae_encoder(
            checkpoint_path=audio_vae_file,
            device=torch_device,
            dtype=torch.float32,  # Audio VAE needs float32 for quality.
        )
        audio_processor = AudioProcessor(
            target_sample_rate=audio_vae_encoder.sample_rate,
            mel_bins=audio_vae_encoder.mel_bins,
            mel_hop_length=audio_vae_encoder.mel_hop_length,
            n_fft=audio_vae_encoder.n_fft,
        ).to(torch_device)

    # batch_size=1: audio clips have variable length and cannot be collated into a single batch.
    dataloader = DataLoader(dataset, batch_size=1, shuffle=False, num_workers=4)

    success_count = 0
    skip_count = 0

    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        BarColumn(),
        TaskProgressColumn(),
        MofNCompleteColumn(),
        TimeElapsedColumn(),
        TimeRemainingColumn(),
        console=console,
    ) as progress:
        task = progress.add_task("Processing audio", total=len(dataloader))

        for batch in dataloader:
            relative_path = batch["relative_path"][0]
            output_rel_path = Path(relative_path).with_suffix(".pt")
            output_file = output_path / output_rel_path

            try:
                audio_data = Audio(
                    waveform=batch["waveform"][0],
                    sampling_rate=batch["sample_rate"][0].item(),
                )

                with torch.inference_mode():
                    audio_latents = encode_audio(audio_vae_encoder, audio_processor, audio_data)

                output_file.parent.mkdir(parents=True, exist_ok=True)

                audio_save_data = {
                    "latents": audio_latents["latents"].cpu().contiguous(),
                    "num_time_steps": audio_latents["num_time_steps"],
                    "frequency_bins": audio_latents["frequency_bins"],
                    "duration": audio_latents["duration"],
                }

                torch.save(audio_save_data, output_file)
                success_count += 1
            except Exception as e:
                logger.warning(f"Failed to encode audio {relative_path}: {e}")
                skip_count += 1

            progress.advance(task)

    logger.info(f"Audio processing: {success_count} encoded, {skip_count} skipped. Latents saved to {output_path}")


def preprocess_audio_dataset(
    dataset_file: str,
    caption_column: str,
    audio_column: str,
    output_dir: str | None,
    model_path: str,
    text_encoder_path: str,
    device: str,
    audio_vae_path: str | None = None,
    lora_trigger: str | None = None,
    remove_llm_prefixes: bool = False,
    load_text_encoder_in_8bit: bool = False,
    max_duration: float | None = None,
) -> None:
    """Run the audio-only preprocessing pipeline (conditions/ + audio_latents/)."""
    # Import here to avoid loading the text-encoder stack unless needed.
    from process_captions import compute_captions_embeddings

    _validate_dataset_file(dataset_file)

    output_base = Path(output_dir) if output_dir else Path(dataset_file).parent / ".precomputed"
    conditions_dir = output_base / "conditions"
    audio_latents_dir = output_base / "audio_latents"

    if lora_trigger:
        logger.info(f'LoRA trigger word "{lora_trigger}" will be prepended to all captions')

    with free_gpu_memory_context():
        compute_captions_embeddings(
            dataset_file=dataset_file,
            output_dir=str(conditions_dir),
            model_path=model_path,
            text_encoder_path=text_encoder_path,
            caption_column=caption_column,
            media_column=audio_column,
            lora_trigger=lora_trigger,
            remove_llm_prefixes=remove_llm_prefixes,
            batch_size=1,
            device=device,
            load_in_8bit=load_text_encoder_in_8bit,
        )

    with free_gpu_memory_context():
        compute_audio_latents(
            dataset_file=dataset_file,
            audio_column=audio_column,
            output_dir=str(audio_latents_dir),
            model_path=model_path,
            audio_vae_path=audio_vae_path,
            device=device,
            max_duration=max_duration,
        )

    logger.info(f"Audio dataset preprocessing complete! Results saved to {output_base}")
    logger.info("Audio latents saved to audio_latents/ and text embeddings to conditions/ (no video latents/).")


def _validate_dataset_file(dataset_path: str) -> None:
    """Validate that the dataset file exists and has the correct format."""
    dataset_file = Path(dataset_path)

    if not dataset_file.exists():
        raise FileNotFoundError(f"Dataset file does not exist: {dataset_file}")

    if not dataset_file.is_file():
        raise ValueError(f"Dataset path must be a file, not a directory: {dataset_file}")

    if dataset_file.suffix.lower() not in [".csv", ".json", ".jsonl"]:
        raise ValueError(f"Dataset file must be CSV, JSON, or JSONL format: {dataset_file}")


@app.command()
def main(
    dataset_path: str = typer.Argument(
        ...,
        help="Path to metadata file (CSV/JSON/JSONL) containing captions and audio paths",
    ),
    model_path: str = typer.Option(
        ...,
        help="Path to a unified LTX checkpoint or split-pack transformer (.safetensors file)",
    ),
    text_encoder_path: str = typer.Option(
        ...,
        help="Path to the Gemma text encoder directory, or the packed text-encoder safetensors of a split pack",
    ),
    audio_vae_path: str | None = typer.Option(
        default=None,
        help="Audio VAE safetensors (required for a split LTX-2.5 pack)",
    ),
    caption_column: str = typer.Option(
        default="caption",
        help="Column name containing captions in the dataset JSON/JSONL/CSV file",
    ),
    audio_column: str = typer.Option(
        default="media_path",
        help="Column name containing audio paths in the dataset JSON/JSONL/CSV file",
    ),
    device: str = typer.Option(
        default="cuda",
        help="Device to use for computation",
    ),
    output_dir: str | None = typer.Option(
        default=None,
        help="Output directory (defaults to .precomputed in dataset directory)",
    ),
    lora_trigger: str | None = typer.Option(
        default=None,
        help="Optional trigger word to prepend to each caption (activates the LoRA during inference)",
    ),
    remove_llm_prefixes: bool = typer.Option(
        default=False,
        help="Remove LLM prefixes from captions",
    ),
    load_text_encoder_in_8bit: bool = typer.Option(
        default=False,
        help="Load the Gemma text encoder in 8-bit precision to save GPU memory (requires bitsandbytes)",
    ),
    max_duration: float | None = typer.Option(
        default=None,
        help="Optional maximum audio duration in seconds. Longer clips are trimmed to bound memory use.",
    ),
) -> None:
    """Preprocess a standalone audio dataset for mixed audio-video training.

    The dataset must be a CSV, JSON, or JSONL file with columns for captions and audio paths.
    Writes conditions/ (text embeddings) and audio_latents/ into the precomputed directory, but
    intentionally does NOT write video latents/, marking these as audio-only samples.

    Examples:
        # Process an audio dataset (output to dataset_dir/.precomputed)
        python scripts/process_audio.py dataset.csv \\
            --model-path /path/to/ltx2.safetensors --text-encoder-path /path/to/gemma

        # Custom column names and capped duration
        python scripts/process_audio.py dataset.json \\
            --model-path /path/to/ltx2.safetensors --text-encoder-path /path/to/gemma \\
            --caption-column "text" --audio-column "audio_path" --max-duration 10.0
    """
    preprocess_audio_dataset(
        dataset_file=dataset_path,
        caption_column=caption_column,
        audio_column=audio_column,
        output_dir=output_dir,
        model_path=model_path,
        text_encoder_path=text_encoder_path,
        device=device,
        audio_vae_path=audio_vae_path,
        lora_trigger=lora_trigger,
        remove_llm_prefixes=remove_llm_prefixes,
        load_text_encoder_in_8bit=load_text_encoder_in_8bit,
        max_duration=max_duration,
    )


if __name__ == "__main__":
    app()
