model:
  model_path: /path/to/ltx-2.3-22b-dev.safetensors
  text_encoder_path: /path/to/google/gemma-3-12b-it
  training_mode: lora
  load_checkpoint: null
lora:
  rank: 48
  alpha: 48
  dropout: 0.05
  target_modules:
  - to_k
  - to_q
  - to_v
  - to_out.0
  - to_gate_logits
  - net.0.proj
  - net.2
training_strategy:
  name: text_to_video
  first_frame_conditioning_p: 1.0
  with_audio: true
  audio_latents_dir: audio_latents
  h_flip: true
  first_frame_conditioning_noise: 0.0
  temporal_boundary_loss_weight: 1.2
  temporal_boundary_frames: 3
optimization:
  learning_rate: 0.00001
  steps: 11200
  batch_size: 1
  gradient_accumulation_steps: 1
  max_grad_norm: 1.0
  optimizer_type: muon
  optimizer_params:
    adjust_lr_fn: match_rms_adamw
    weight_decay: 0.0001
  scheduler_type: lambda_warmup
  scheduler_params:
    num_warmup_steps: 560
  enable_gradient_checkpointing: true
acceleration:
  mixed_precision_mode: 'bf16'
  quantization: null
  load_text_encoder_in_8bit: false
data:
  preprocessed_data_root: /path/to/videos/.precomputed
  num_dataloader_workers: 4
validation:
  prompts:
  - prompt_1
  - prompt_2
  images:
  - /path/to/image_1.jpeg
  - /path/to/image_2.jpeg
  negative_prompt: worst quality, inconsistent motion, blurry, jittery, distorted
  video_dims:
  - 416
  - 608
  - 241
  frame_rate: 24.0
  seed: 42
  inference_steps: 30
  interval: 560
  videos_per_prompt: 1
  guidance_scale: 3.0
  stg_scale: 0.0
  stg_blocks: [ 28 ]
  stg_mode: stg_av
  generate_audio: true
  skip_initial_validation: false
checkpoints:
  interval: 560
  keep_last_n: -1
  precision: bfloat16
  no_resume: true
flow_matching:
  timestep_sampling_mode: uniform
  timestep_sampling_params: {}
  timestep_loss_weighting: "weighted"
hub:
  push_to_hub: false
  hub_model_id: null
trackio:
  enabled: true
  project: "ltx-2-trainer"
  space_id: null
  log_validation_videos: false
seed: 42
output_dir: /path/to/outputs
